# This is a basic workflow that is manually triggered

name: 01a Hola mundo

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
jobs:
  # This workflow contains a single job called "greet"
  hola-mundo:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Hola mundo
      run: echo "Hola mundo!"
